### ISSUE TITLE
assert self.link_tokenizer is not None

### ISSUE THREAD

**Issue by RSZZZJC** [Phimos/SIGSPATIAL-2021-GISCUP-3rd-Solution#1]
File "C:\Users\jackie\PycharmProjects\ETA\SIGSPATIAL-2021-GISCUP-2nd-Place-Solution-main\dataset.py", line 461, in link_num
    assert self.link_tokenizer is not None

请问程序中的tokenizer如何设置？感谢解答。

**Comment by Phimos** [comment]
感谢您的关注。Tokenizer实际上是将link/driver的id进行映射的工具，比如在split_k_fold里面第348行会进行tokenizer的生成，或者你可以理解为NLP里面词表到index的映射。这边是基于train set的id进行映射构造的。可以对train_set调用generate_tokenizer方法，之后在valid和test集合当中利用load_tokenizer方法，保证所有tokenizer相同即可。

如果开源代码对您有帮助希望您可以给个star~
