### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by lihualilee** [Phimos/SIGSPATIAL-2021-GISCUP-3rd-Solution#2]
现在官网上下载到的数据集与代码中使用到的数据不一致，请问可以提供一份数据嘛，非常感谢您的回复

**Comment by Phimos** [comment]
不好意思，我这边没有保存原始的数据集

关于原始数据的数据格式可以参考：

https://sigspatial2021.sigspatial.org/sigspatial-cup/
